project_id = "uyhzhlgoiveljgdsyugn"

[functions.dfy-provision]
verify_jwt = false

[functions.create-payfast-payment]
verify_jwt = false

[functions.payfast-webhook]
verify_jwt = false

[functions.get-order]
verify_jwt = false
