project_id = "uyhzhlgoiveljgdsyugn"

[functions.dfy-provision]
verify_jwt = false

[functions.create-payfast-payment]
verify_jwt = false

[functions.payfast-webhook]
verify_jwt = false

[functions.get-order]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-campaign-email]
verify_jwt = false

[functions.process-drip-emails]
verify_jwt = false

[functions.get-drip-sequences]
verify_jwt = false

[functions.update-drip-sequence]
verify_jwt = false

[functions.get-leads]
verify_jwt = false
